-- augName -> parameter name.value (per-row, precomputed & escaped)
-- Generated by generate_augname_update.py. Run inside a transaction.
-- Windows-forbidden filename chars (\ / : * ? " < > | + control) replaced with '_'.
-- rows to change: 51  (skipped-equal: 130, miss: 0, sanitized-names: 51)
-- WARNING: 치환 후 이름 중복 발생:
--   '#D_L FORK 인버터': ids=[204, 226]
--   '#D_L 인버터': ids=[203, 225]
--   '#O_H 인버터': ids=[205, 227]

BEGIN TRANSACTION;
UPDATE asset SET parameter='{
  plc {
    name {
      type = Text,
      value = "E_ROOM LINE PLC"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    setting {
      IP {
        type = Hidden,
        value = ""
      },
      project {
        type = File,
        value = "C://twms//Setup//LayoutDesigner//AssetPrj//EROOM//PLC//PLC.xgwx",
        filter = "XGWX File | *.xgwx"
      },
      password {
        type = Password,
        value = ""
      }
    },
    trigger {
      type = check,
      value = "false"
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=5;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#102_103_104 공정조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.12"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=8;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#반입_반출_ ROLL BED 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.14"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=10;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "108 D_L 상_하강"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.10"
          },
          base number {
            type = Numeric,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Numeric,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.1.8.141"
        },
        modelName {
          type = Selection,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Version,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=12;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "131 D_L 상_하강"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.10"
          },
          base number {
            type = Numeric,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Numeric,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.1.8.143"
        },
        modelName {
          type = Selection,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Version,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=13;
UPDATE asset SET parameter='{
  plc {
    name {
      type = Text,
      value = "U_B1 #121~134 LINE CPU"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    setting {
      IP {
        type = Hidden,
        value = ""
      },
      project {
        type = File,
        value = "C://twms//Setup//LayoutDesigner//AssetPrj//UB1//PLC//PLC1.xgwx",
        filter = "XGWX File | *.xgwx"
      },
      password {
        type = Password,
        value = ""
      }
    },
    trigger {
      type = check,
      value = "false"
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=16;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#121_131 공정 조작반(0)"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.21"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=18;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#133_134 공정 조작반(0)"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.22"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=19;
UPDATE asset SET parameter='{
  plc {
    name {
      type = Text,
      value = "U_B1 #135~셔틀 LINE CPU"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    setting {
      IP {
        type = Hidden,
        value = ""
      },
      project {
        type = File,
        value = "C://twms//Setup//LayoutDesigner//AssetPrj//UB2//PLC//PLC2.xgwx",
        filter = "XGWX File | *.xgwx"
      },
      password {
        type = Password,
        value = ""
      }
    },
    trigger {
      type = check,
      value = "false"
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=22;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#135_136 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.31"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=24;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#137_셔틀 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.32"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=25;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#137 D_L 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.33"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=26;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "137 D_L 상_하강"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.30"
          },
          base number {
            type = Numeric,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Numeric,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.3.8.141"
        },
        modelName {
          type = Selection,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Version,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=28;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "137 D_L FORK"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.30"
          },
          base number {
            type = Numeric,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Numeric,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.3.8.143"
        },
        modelName {
          type = Selection,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Version,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=29;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "301 D_L 상_하강"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.40"
          },
          base number {
            type = Numeric,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Numeric,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.4.8.143"
        },
        modelName {
          type = Selection,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Version,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=39;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "#306공정 R_Buck공정조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.51"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=44;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "300-1-2_2-1_4-10 공정조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.82"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=64;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Text,
      value = "300-2-9_3-2_4-1  공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.84"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=66;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "300-1-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.80"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.8.8.141"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=68;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "300-3-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.80"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.8.8.151"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=73;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "500-1-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.100"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.10.8.141"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=86;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "500-3-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.100"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.10.8.147"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=89;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "600-1-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.150"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.15.8.141"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=101;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "600-3-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.150"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.15.8.147"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=104;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "800-1-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "7",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.7.141"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=122;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "800-3-1 DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "7",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.7.149"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.05"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=126;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.8.149"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.10"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=140;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "O_H 1 셔틀 주행"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.8.153"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=142;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "O_H 1 셔틀 상_하"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.8.155"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=143;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "O_H 2 셔틀 주행"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.8.161"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=146;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "O_H 2 셔틀 상_하"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.8.163"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=147;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "963_DL UP_DOWN"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.160"
          },
          base number {
            type = String,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = String,
            value = "6",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.16.6.147"
        },
        modelName {
          type = String,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = String,
          value = "1.05"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=153;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#201_202 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.181"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=190;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#203_204 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.182"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=191;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#205_206 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.191"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=195;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#207_208 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.192"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=196;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#214_DL취출 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.201"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=200;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "이송기1_OH_이송기2 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.202"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=201;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#209_212 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.203"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=202;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#D_L 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.200"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.20.8.140"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=203;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#D_L FORK 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.200"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.20.8.142"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=204;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#O_H 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.200"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.20.8.144"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=205;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#221_222 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.211"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=212;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#223_224 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.212"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=213;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#225_226 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.221"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=217;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#227_228 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.222"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=218;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#234_DL 공정 조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.231"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=222;
UPDATE asset SET parameter='{
  hmi {
    name {
      type = Bool,
      value = "#229_232 공정조작반"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      IP {
        type = IPAddress,
        value = "120.200.200.233"
      },
      optionType {
        type = Selection,
        value = "TCP",
        candidates = [TCP]
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=224;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#D_L 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.230"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.23.8.140"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.04"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=225;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#D_L FORK 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.230"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.23.8.142"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=226;
UPDATE asset SET parameter='{
  drive {
    name {
      type = Text,
      value = "#O_H 인버터"
    },
    description {
      type = Memo,
      value = "Description, here"
    },
    connections {
      Via Connections {
        type = Button,
        value = "+",
        1 depth {
          type = Button,
          value = "-",
          visible = True,
          optionType {
            type = Selection,
            value = "TCP",
            candidates = [TCP]
          },
          connection {
            type = IPAddress,
            value = "120.200.200.230"
          },
          base number {
            type = Bool,
            value = "0",
            minmax = "0,99"
          },
          slot number {
            type = Bool,
            value = "8",
            minmax = "0,99"
          }
        }
      },
      Destination {
        IP {
          type = IPAddress,
          value = "200.23.8.144"
        },
        modelName {
          type = Bool,
          value = "iS7",
          candidates = [S100,H100,G100,iS7,S300]
        },
        modelVersion {
          type = Bool,
          value = "1.02"
        },
        optionType {
          type = Selection,
          value = "TCP",
          candidates = [TCP]
        }
      }
    },
    retrial {
      type = Numeric,
      value = "2",
      minmax = "0,9"
    },
    max count {
      type = Numeric,
      value = "30",
      minmax = "0,100000"
    }
  }
}' WHERE id=227;
COMMIT;
