# -*- coding: utf-8 -*-
r"""
augName -> parameter HOCON name.value 행별 UPDATE SQL 생성기.

DEXA asset 테이블의 augName 값을 parameter 문자열의 name.value 자리에 치환하는
UPDATE 문을 행별로 생성한다 (위치기반 CTE 방식은 구버전 sqlite3에서 실패하므로
Python으로 완전 계산 후 이스케이프된 개별 UPDATE 를 만든다 — sqlite 버전 무관).

name.value 4형식 모두 처리:
  점표기 + 작은따옴표   name.value = 'HMI3'
  점표기 + 큰따옴표     name.value = "309LH_FEEDER"
  블록형 + 작은따옴표   name { ... value = '...' }
  블록형 + 큰따옴표     name { ... value = "..." }

Windows 파일명 금지 문자 치환:
  DEXA 서버는 백업 zip 을 Storage/Backup/{id}/{ver}/{자산이름}.zip 으로
  저장/조회하므로 이름의 \ / : * ? " < > | 및 제어문자는 백업을 파괴한다.
  → name.value 에 넣기 전에 전부 '_' 로 치환한다. (augName 컬럼 원본은 불변)

사용법:
  python generate_augname_update.py [DB경로] [출력SQL경로]
  기본값: C:\\ProgramData\\LS\\DEXA\\Storage\\DEXA.sqlite3 , augname_update_generated.sql (스크립트 위치)

주의: DB 는 읽기 전용으로만 연다. 생성된 SQL 적용 전 반드시 DB 백업.
"""
import os
import re
import sqlite3
import sys

DEFAULT_DB = r"C:\ProgramData\LS\DEXA\Storage\DEXA.sqlite3"
FORBIDDEN = re.compile(r'[\\/:*?"<>|\x00-\x1f]')


def sanitize(name: str) -> str:
    """Windows 파일명 금지 문자를 '_' 로 치환하고 앞뒤 공백을 제거한다."""
    return FORBIDDEN.sub("_", name).strip()


def find_name_value(param: str):
    """parameter 문자열에서 name.value 의 (여는따옴표 위치, 닫는따옴표 위치, 따옴표문자) 반환.

    앵커: 'name.value' 가 있으면 그 지점, 없으면 'name {' 뒤의 첫 'value'.
    값: 앵커 뒤 첫 '=' 다음에 나오는 첫 따옴표(' 또는 ")부터 같은 종류 닫는 따옴표까지.
    실패 시 None.
    """
    i = param.find("name.value")
    if i < 0:
        b = param.find("name {")
        if b < 0:
            return None
        i = param.find("value", b)
        if i < 0:
            return None
    eq = param.find("=", i)
    if eq < 0:
        return None
    dq = param.find('"', eq + 1)
    sq = param.find("'", eq + 1)
    if dq < 0 and sq < 0:
        return None
    if dq >= 0 and (sq < 0 or dq < sq):
        o, qc = dq, '"'
    else:
        o, qc = sq, "'"
    c = param.find(qc, o + 1)
    if c < 0:
        return None
    return o, c, qc


def hocon_escape(value: str, quote: str) -> str:
    """HOCON 문자열 값 이스케이프: 백슬래시와 감싸는 따옴표만 처리."""
    return value.replace("\\", "\\\\").replace(quote, "\\" + quote)


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main():
    db_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "augname_update_generated.sql")

    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    rows = con.execute(
        "SELECT id, augName, parameter FROM asset"
        " WHERE deleted = 0 AND augName IS NOT NULL AND augName <> ''"
    ).fetchall()
    con.close()

    updates, skipped_equal, misses, sanitized_ids = [], 0, [], []
    final_names = {}  # sanitized name -> [asset ids] (치환 후 이름 중복 검사)

    for aid, aug, param in rows:
        new_name = sanitize(aug)
        final_names.setdefault(new_name, []).append(aid)
        if new_name != aug:
            sanitized_ids.append(aid)

        loc = find_name_value(param or "")
        if loc is None:
            misses.append(aid)
            continue
        o, c, qc = loc
        current = param[o + 1:c]
        if current == new_name:
            skipped_equal += 1
            continue
        new_param = param[:o + 1] + hocon_escape(new_name, qc) + param[c:]
        updates.append((aid, current, new_name, new_param))

    dups = {n: ids for n, ids in final_names.items() if len(ids) > 1}

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- augName -> parameter name.value (per-row, precomputed & escaped)\n")
        f.write("-- Generated by generate_augname_update.py. Run inside a transaction.\n")
        f.write("-- Windows-forbidden filename chars (\\ / : * ? \" < > | + control) replaced with '_'.\n")
        f.write(f"-- rows to change: {len(updates)}  (skipped-equal: {skipped_equal},"
                f" miss: {len(misses)}, sanitized-names: {len(sanitized_ids)})\n")
        if misses:
            f.write(f"-- MISS (name.value 미검출, 수동 확인 필요): {misses}\n")
        if dups:
            f.write("-- WARNING: 치환 후 이름 중복 발생:\n")
            for n, ids in sorted(dups.items()):
                f.write(f"--   {n!r}: ids={ids}\n")
        f.write("\nBEGIN TRANSACTION;\n")
        for aid, _cur, _new, new_param in updates:
            f.write(f"UPDATE asset SET parameter={sql_quote(new_param)} WHERE id={aid};\n")
        f.write("COMMIT;\n")

    print(f"generated: {out_path}")
    print(f"rows to change: {len(updates)}, skipped-equal: {skipped_equal}, miss: {len(misses)}")
    print(f"sanitized (forbidden chars found): {len(sanitized_ids)} -> {sanitized_ids}")
    if dups:
        print("WARNING: duplicate names after sanitize:")
        for n, ids in sorted(dups.items()):
            print(f"  {n!r}: ids={ids}")
    for aid, cur, new, _ in updates[:200]:
        print(f"  id={aid}: {cur!r} -> {new!r}")


if __name__ == "__main__":
    main()
